name: Distance Calculator CI/CD

# Запуск workflow при push и pull request в main ветку
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: '*'

# Переменные окружения
env:
  PYTHON_VERSION: '3.9'
  NODE_VERSION: '18'

jobs:
  # Проверка и тестирование Python бэкенда
  backend-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov flake8
    
    - name: Lint with flake8
      run: |
        # Остановка сборки если есть синтаксические ошибки или неопределенные переменные
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # Проверка стиля кода (предупреждения, не критично)
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Test Flask app startup
      run: |
        # Тест что приложение запускается без ошибок
        python -c "
        import app
        print('Flask app imports successfully')
        
        # Проверяем что все endpoints доступны
        with app.app.test_client() as client:
            response = client.get('/health')
            assert response.status_code == 200
            print('Health endpoint works')
            
            response = client.get('/')
            assert response.status_code == 200
            print('Root endpoint works')
        "
    
    - name: Test file upload (mock)
      run: |
        # Тест загрузки файла
        python -c "
        import app
        import tempfile
        import os
        
        # Создаем тестовый файл
        with tempfile.NamedTemporaryFile(suffix='.jpg', delete=False) as f:
            f.write(b'fake image data for testing')
            test_file = f.name
        
        try:
            with app.app.test_client() as client:
                with open(test_file, 'rb') as f:
                    data = {'file': (f, 'test.jpg')}
                    response = client.post('/upload', 
                                         content_type='multipart/form-data',
                                         data=data)
                    print(f'Upload response status: {response.status_code}')
                    print('Upload endpoint accessible')
        finally:
            os.unlink(test_file)
        "

  # Проверка фронтенда
  frontend-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
    
    - name: Validate HTML
      run: |
        # Устанавливаем html5validator для проверки HTML
        pip install html5validator
        
        # Проверяем HTML файл на валидность
        html5validator --root . --match "*.html" --log INFO || true
        echo "HTML validation completed"
    
    - name: Check for common issues
      run: |
        # Проверяем что в HTML нет проблемных паттернов
        echo "Checking HTML for common issues..."
        
        # Проверяем что есть DOCTYPE
        if ! grep -q "<!DOCTYPE html>" *.html; then
          echo "Warning: No DOCTYPE found in HTML files"
        fi
        
        # Проверяем что есть метатеги
        if ! grep -q "charset=" *.html; then
          echo "Warning: No charset meta tag found"
        fi
        
        # Проверяем что есть viewport для мобильных
        if ! grep -q "viewport" *.html; then
          echo "Warning: No viewport meta tag found"
        fi
        
        echo "Frontend check completed"

  # Интеграционные тесты
  integration-test:
    runs-on: ubuntu-latest
    needs: [backend-test, frontend-check]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install requests
    
    - name: Start Flask server in background
      run: |
        python app.py &
        echo $! > flask.pid
        
        # Ждем пока сервер запустится
        sleep 5
        
        # Проверяем что сервер отвечает
        curl -f http://localhost:5000/health || exit 1
        echo "Flask server started successfully"
    
    - name: Test API endpoints
      run: |
        # Тестируем основные endpoints
        echo "Testing API endpoints..."
        
        # Health check
        curl -f http://localhost:5000/health
        echo "✓ Health endpoint works"
        
        # Root endpoint
        curl -f http://localhost:5000/
        echo "✓ Root endpoint works"
        
        # App page
        curl -f http://localhost:5000/app
        echo "✓ App endpoint works"
        
        echo "All API tests passed!"
    
    - name: Cleanup
      run: |
        # Останавливаем Flask сервер
        if [ -f flask.pid ]; then
          kill $(cat flask.pid) || true
          rm flask.pid
        fi

  # Проверка безопасности
  security-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    
    - name: Install security tools
      run: |
        python -m pip install --upgrade pip
        pip install safety bandit
    
    - name: Check for known vulnerabilities in dependencies
      run: |
        pip install -r requirements.txt
        safety check --json || true
        echo "Safety check completed"
    
    - name: Run bandit security linter
      run: |
        bandit -r . -f json || true
        echo "Bandit security check completed"

  # Сборка Docker образа (опционально)
  docker-build:
    runs-on: ubuntu-latest
    needs: [backend-test, frontend-check]
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Create Dockerfile
      run: |
        cat > Dockerfile << 'EOF'
        FROM python:3.9-slim
        
        WORKDIR /app
        
        # Копируем файлы зависимостей
        COPY requirements.txt .
        
        # Устанавливаем зависимости
        RUN pip install --no-cache-dir -r requirements.txt
        
        # Копируем код приложения
        COPY . .
        
        # Создаем необходимые папки
        RUN mkdir -p uploads processed
        
        # Открываем порт
        EXPOSE 5000
        
        # Запускаем приложение
        CMD ["python", "app.py"]
        EOF
    
    - name: Build Docker image
      run: |
        docker build -t distance-calculator:latest .
        echo "Docker image built successfully"
    
    - name: Test Docker container
      run: |
        # Запускаем контейнер в фоне
        docker run -d --name test-container -p 5000:5000 distance-calculator:latest
        
        # Ждем запуска
        sleep 10
        
        # Тестируем что контейнер работает
        curl -f http://localhost:5000/health || exit 1
        echo "Docker container test passed"
        
        # Останавливаем контейнер
        docker stop test-container
        docker rm test-container

  # Деплой (только для main ветки)
  deploy:
    runs-on: ubuntu-latest
    needs: [integration-test, security-check]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Deploy notification
      run: |
        echo "🚀 Ready for deployment!"
        echo "All tests passed, security checks completed"
        echo "Project is ready for production deployment"
        
        # Здесь можно добавить реальный деплой:
        # - Heroku
        # - AWS
        # - Digital Ocean
        # - Своей сервер
        
        echo "Deployment step completed"

  # Уведомления о статусе
  notify:
    runs-on: ubuntu-latest
    needs: [backend-test, frontend-check, integration-test, security-check]
    if: always()
    
    steps:
    - name: Notify build status
      run: |
        if [ "${{ needs.backend-test.result }}" == "success" ] && \
           [ "${{ needs.frontend-check.result }}" == "success" ] && \
           [ "${{ needs.integration-test.result }}" == "success" ] && \
           [ "${{ needs.security-check.result }}" == "success" ]; then
          echo "✅ All checks passed! Build successful."
        else
          echo "❌ Some checks failed. Please review the logs."
          exit 1
        fi